#!/bin/sh
#
#
help()
{
	echo 'Usage: pythonjob python_file [output_file]'
	echo ' '
	echo '	This command runs a set of Python instructions'
	echo '	in a non-interactive enviroment.'
	echo ' '
	echo '  If the output_file is not specificed, the output is directed to stdout'
	echo '	(which, is on screen if a screen is present).'
	echo ' '
}

if test -z "$1"
then
	help
	exit 1
else
	if test -f "$1"
	then
		if test -z "$2"
		then
			# no output
			python "$1"
		else
			python "$1" > "$2"
		fi
	else
		echo "$1" "is not a file"
	fi
fi

