#!/bin/sh
#
#  script for submitting batch mode Python jobs to the sun grid engine.
#
# 14 January 2009     Andrew Hills
#
help()
{
echo ' THIS COMMAND SUBMITS PYTHON JOBS TO THE SUN GRID ENGINE '
echo ' ------------------------------------------------------- '
echo ' Usage:    qpy python_script_file  -time hh:mm:ss [-nq] [-em email@address.ac.uk] -name text'
echo ' Where; '
echo '    python_script_file is a file containing a series of Python commands.'
echo '    hh:mm:ss is the cpu time needed in hours:minutes:seconds '
echo '    -nq is an optional parameter to submit without confirming '
echo '    -em is an optional parameter to activate email functionality '
echo '    -name is an optional parameter to give the script a name ' 
echo '    '
echo ' Example: qpy test1.py -time 00:30:00 '
echo '    '
echo ' Python_script_files are essentially a sequence of Python Commands.'
echo '    '
echo ' You should not attempt to use Python commands that result in graphical'
echo ' output to the screen when running in batch mode.'
echo ' If you wish to experiment with Python in batch environment you can start'
echo ' it up by starting a Qsh session and running Python as: '
echo ' '
echo '    python '
echo ' '
}
 
# check the Python script file

if test -z "$1" ; then
	echo ' '
	echo "**the script file containing the Python commands was not specified."
	echo ' '
        help
	exit 1
else 
       if test -r "$1" ; then
# debug           echo " Using file '$2' as Python commands file"
           pyscrpt="$1"
       else
           echo " Specified Python Scripts file '$1' does not exist or is not accesible."
           exit 1
       fi
fi

#
# below is a template for accessing the keyword parameters. There is only one 
# now but can increase later.
# 
time="notset"
subnow="0"
emailout=" "
pname=" "
while [ $# -gt 0 ]; do
#  echo $1
  case $1 in

     -time|-TIME) time="$2";shift;;
     -out|-OUT) output="$2";shift;;
     -nq|-NQ) subnow="1";;
	 -em|-EM) emailout="-m ea -M $2";shift;;
	 -name|-NAME) pname="-N $2";shift;;
  esac
  shift
done
if test "$output" != " "; then
	if test -e "$output" ; then
		echo " The specified output file '$output' already exists."
		exit 1
	fi
fi
		 

# debug echo $time
if test "$time" = "notset" ; then
   echo -e '\nTime parameter was not specified. Assuming it to be 1 hour.'
   echo '                                            i.e. -time 01:00:00 '
   time="01:00:00"
fi

echo -e 'A Python job to execute the Python commands in <' $pyscrpt '>' 
echo 'will be submitted.'
 
echo 'Maximum cpu time specified (hh:mm:ss) is :' $time 

if test "$subnow" = "0"
 then
    echo -e '\n\r Do you wish to submit this job (Yes/No) ? \c' 
    read answ
    if test "$answ" = "Y" -o "$answ" = "y" -o "$answ" = "YES" -o "$answ" = "yes" -o "$answ" = "Yes" -o "$answ" = "ye"   
     then
     subnow="1" 
    fi
fi

if test "$subnow" = "1" 
 then

echo -e ' \n\r The command used to submit the job is:'
echo ' qsub -S /bin/sh -l h_cpu='$time ' ' $emailout '-cwd ~/bin/pythonjob` ' $pyscrpt 
qsub -S /bin/sh -l h_cpu=$time $emailout $pname -cwd ~/bin/pythonjob $pyscrpt $output
   echo 'Use the Qstat command to check progress of the job.' 
  else
    echo 'Job Aborted.....'
  fi


